### ISSUE TITLE
В списке разрешенных расширений для таблиц данных должны быть xls и xlsx

### ISSUE THREAD

**Issue by zmm** [OSLL/templater#5]
Сейчас в расширениях есть только csv
![image](https://user-images.githubusercontent.com/717575/89046084-2e424f80-d355-11ea-911f-1c00c9405230.png)

**Comment by levi218** [comment]
![image](https://user-images.githubusercontent.com/31766219/89050077-e292a480-d35a-11ea-9a92-6d0ab2cc7281.png)
В Windows может выбрать все 3 типа (CSV, XLS, XLSX). Типы не отображали правильно, возможно, потому что я поместил их MIME-тип вместо расширения. Теперь он должен отображаться правильно. Пожалуйста, посмотрите
